main: cn.wode490390.nukkit.skyplaingen.SkyPlainGeneratorPlugin
name: "SkyPlainGenerator"
author: "wode490390"
description: "Sky plain generator plugin for Nukkit"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.11"]
load: STARTUP
